### ISSUE TITLE
ASK - Console.log the result

### ISSUE THREAD

**Issue by yogieputra8** [voucherifyio/voucher-code-generator-js#10]
So, i tried this library and here's the codes:

```
var voucher_codes = require('voucher-code-generator');

voucher_codes.generate({
    length: 8,
    count: 5
});

```

I want to console.log the result from the function. How can I do that?

**Comment by yogieputra8** [comment]
Ahh, finally I solved the issue just add few codes from the sample in test folder.

```
var voucher_codes = require('voucher-code-generator');

var basicCodes = voucher_codes.generate({
    length: 6,
    count: 5
});
console.log(basicCodes)
```

I close this issue now. Thanks

**Comment by LukaszWiktor** [comment]
No problem @yogieputra8! Happy coding ;)
