### ISSUE TITLE
Unique set of 200,000

### ISSUE THREAD

**Issue by osi-bhushankumar** [voucherifyio/voucher-code-generator-js#13]
If I use below function at a while for generating up to 200,000 codes, does it guarantee that I always get unique number ?

`voucher_codes.generate({
    pattern: "##-###-##",
});
`

**Comment by LukaszWiktor** [comment]
Yes, it's always guaranteed that the voucher-code-generator produces a list of unique codes, unless the requested count is greater then the number of all possible codes for given config. In your case it's absolutely possible to generate 200,000 numeric codes that follow the pattern `##-###-##` and the upper limit is 10,000,000. Above the limit you will get an error saying `"Not possible to generate requested number of codes."`
